import NavBar from "@/components/NavBar/NavBar";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Banner from "@/components/Banner/Banner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <div className="flex flex-col h-screen justify-between">
          <NavBar />
          <main className="overflow-auto">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
